fullnameOverride: postgres

global:
  postgresql:
    password: ${password}
  pgpool:
    adminPassword: ${password}

postgresqlImage:
  registry: ${pg_registry}
  repository: ${pg_repository}
  tag: ${pg_version}
  debug: ${debug}

pgpoolImage:
  debug: ${debug}

metricsImage:
  debug: ${debug}

postgresql:
  replicaCount: ${replica_count}
  repmgrLogLevel: DEBUG
  repmgrReconnectInterval: 10
  initdbScripts:
    odahu_init.sh: |
      #!/usr/bin/env bash
      DBS="${databases}"
      for db in $${DBS}; do
        echo "Creating database $db"
        PGPASSWORD=${password} psql -w -U "postgres" -d "postgres" -h 127.0.0.1 -c "CREATE DATABASE $db"
      done

pgpool:
  replicaCount: 1

metrics:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
  serviceMonitor:
    enabled: true
    selector:
      prometheus: kube-prometheus

persistence:
  enabled: true
  existingClaim: ${pg_volume_name}
  mountPath: /bitnami/postgresql
