apiVersion: v1
kind: ConfigMap
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "webhook") | nindent 4 }}
  name: config-defaults
  namespace: {{ .Release.Namespace }}
        {{- if .Values.config.defaults }}
data:
        {{ toYaml .Values.config.defaults | nindent 2 }}
        {{ else }}
data: {}
        {{- end }}