apiVersion: v1
kind: Service
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "webhook") | nindent 4 }}
  name: webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    role: webhook
