sync:
  volume: "airflow"
  subPath: "${subpath}"   
  target: "s3"
  s3:
    bucket: "${data_bucket_name}"
    region: "${data_bucket_region}"
    authorization: "irsa"

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${iam_role_arn}"

