image: "ubuntu:18.04"

stages:
  - lint
#  - build

# TODO: discuss image building with EPAM support
#docker_images:
#  image: docker:19.03.4
#  stage: lint
#  services:
#    - docker:dind
#  before_script:
#    - apk add -U bash make
#  script:
#    - make docker-build-terraform

shellcheck:
  image: koalaman/shellcheck-alpine:v0.7.0
  stage: lint
  before_script:
    - apk add -U make bash
  script:
    - make shellcheck

terraform:
  image: alpine/terragrunt:0.12.29
  stage: lint
  variables:
    AWS_DEFAULT_REGION: test_region
    TF_PLUGIN_CACHE_DIR: "${CI_PROJECT_DIR}/.terraform.d/plugin-cache"
  before_script:
    - apk add -U make bash findutils
    - mkdir -vp "${TF_PLUGIN_CACHE_DIR}"
  script:
    - make terraform-fmt-check
    - make terraform-validate
    - make terragrunt-fmt-check
  artifacts:
    name: "terraform-plugins"
    paths:
      - ${TF_PLUGIN_CACHE_DIR}/
    expire_in: 1 week
