apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
    monitoring: prometheus
  name: prometheus-grafana-datasource
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://{{ index .Values "prometheus-operator" "fullnameOverride" }}-{{ index .Values "prometheus-operator" "fullnameOverride" }}:9090/
      access: proxy
      isDefault: true