apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring: prometheus
  name: grafana
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: service
  namespaceSelector:
    matchNames:
      - "{{ .Values.namespace }}"
  selector:
    matchLabels:
      app: grafana
