replicaCount: 1
image:
  repository: vault
  tag: ${vault_version}
resources:
  limits:
    cpu: 100m
    memory: 1Gi
service:
  name: https-vault
  type: ClusterIP
  port: 8200
%{ if pgsql_enabled }
persistence:
  enabled: false
%{ else ~}
persistence:
  enabled: true
  size: 5G
  accessMode: ReadWriteOnce
%{ endif ~}

vault:
  externalConfig:
    policies:
      - name: odahu-flow
        rules: path "odahu-flow/connections/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: odahu-flow
            bound_service_account_names:
              - "odahu-flow-api"
              - "odahu-flow-operator"
            bound_service_account_namespaces: ["odahu-flow"]
            policies: odahu-flow
            ttl: 720h
    secrets:
      - path: odahu-flow/connections
        type: kv
        description: ODAHU-flow connection storage.
  config:
    listener:
      tcp:
        address: '0.0.0.0:8200'
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key

    ui: false

%{ if pgsql_enabled }
    storage:
       postgresql:
         connection_url: ${pgsql_url}
%{ else ~}
    storage:
       file:
         path: /vault/file
%{ endif ~}

  logLevel: debug

unsealer:
  image:
    repository: banzaicloud/bank-vaults
    tag: ${vault_unsealer_version}
    pullPolicy: IfNotPresent
  args: [
    "--mode",
    "k8s",
    "--k8s-secret-namespace",
    "${namespace}",
    "--k8s-secret-name",
    "bank-vaults"
  ]
  metrics:
    enabled: false
    debug: ${vault_debug_log_level}

statsd:
  metrics:
    enabled: false
