replicaCount: 1
image:
  repository: vault
  tag: ${vault_version}
dockerizeImage:
  repository: jwilder/dockerize
  tag: 0.6.1
service:
  name: vault
  type: ClusterIP
  port: 8200
persistence:
  enabled: true
  storageClass: "${vault_pvc_storage_class}"
  size: 10G
  accessMode: ReadWriteOnce

vault:
  externalConfig:
    policies:
      - name: odahuflow
        rules: path "odahuflow/connections/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: odahuflow
            bound_service_account_names:
              - "odahuflow-edi"
              - "odahuflow-operator"
            bound_service_account_namespaces: ["odahuflow"]
            policies: odahuflow
            ttl: 720h
    secrets:
      - path: odahuflow/connections
        type: kv
        description: Odahuflow connection storage.
  config:
    listener:
      tcp:
        address: '0.0.0.0:8200'
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key

    ui: false

    storage:
       file:
         path: "/vault/file"

  logLevel: debug

unsealer:
  image:
    repository: banzaicloud/bank-vaults
    tag: 0.5.0
    pullPolicy: IfNotPresent
  args: [
    "--mode",
    "k8s",
    "--k8s-secret-namespace",
    "${namespace}",
    "--k8s-secret-name",
    "bank-vaults"
  ]
  metrics:
    enabled: false
    debug: ${vault_debug_log_level}

statsd:
  metrics:
    enabled: false
