apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
    {{- include "knative.labels" (dict "root" . "name" "networking-istio") | nindent 4 }}
  name: config-istio
  namespace: {{ .Release.Namespace }}
{{- if .Values.config.istio }}
data:
  {{ toYaml .Values.config.istio | nindent 2 }}
{{ else }}
data: {}
{{- end }}
