apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
        {{- include "knative.labels" (dict "root" . "name" "networking-istio") | nindent 4 }}
  name: networking-istio
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
        {{- include "knative.labels" (dict "root" . "name" "networking-istio") | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
          {{- include "knative.labels" (dict "root" . "name" "networking-istio") | nindent 8 }}
    spec:
      containers:
        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.networking_istio.image}}
          name: networking-istio
          ports:
            - containerPort: 9090
              name: metrics
          resources:
                {{ toYaml .Values.networking_istio.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/config-logging
              name: config-logging
      serviceAccountName: controller
      volumes:
        - configMap:
            name: config-logging
          name: config-logging