replicaCount: 1

image:
  repository: quay.io/kubernetes_incubator/nfs-provisioner
  tag: ${version}
  pullPolicy: IfNotPresent

storageClass:
  create: false

rbac:
  create: true

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: ${storage_size}
  storageClass: ${storage_class}
