replicaCount: ${replicas}

image:
  repository: ${repo}
  tag: ${version}
  pullPolicy: IfNotPresent

storageClass:
  create: true
  defaultClass: false
  name: nfs
  allowVolumeExpansion: null
  reclaimPolicy: Delete

rbac:
  create: true

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: ${storage_size}

