apiVersion: v1
kind: ConfigMap
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "autoscaler") | nindent 4 }}
  name: config-autoscaler
  namespace: {{ .Release.Namespace }}
        {{- if .Values.config.autoscaler }}
data:
        {{ toYaml .Values.config.autoscaler | nindent 2 }}
        {{ else }}
data: {}
        {{- end }}
