apiVersion: v1
kind: Service
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "autoscaler") | nindent 4 }}
  name: autoscaler
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: autoscaler