toolchainVersion: "${mlflow_toolchain_version}"
imagesRegistry: "${docker_repo}/"
ingress:
  globalDomain: "${cluster_domain}"
  enabled: true
  tlsEnabled: ${ingress_tls_enabled}
  tlsSecretName: "${ingress_tls_secret_name}"

security:
  enabled: true
  integration: oauth2_proxy
  mesh_authn: "${oauth_mesh_enabled}"

odahuflowctl:
  image: "${docker_repo}/odahu-flow-cli:${odahuflow_version}"

tracking_server:
  annotations:
    sidecar.istio.io/inject: "false"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

toolchain_integration:
  enabled: true

resource_uploader_sa:
  client_id: ${resource_uploader_sa.client_id}
  client_secret: ${resource_uploader_sa.client_secret}

oauth_oidc_issuer_url: ${oauth_oidc_issuer_url}

mlflow_backend_store: "${mlflow_backend_store}"
mlflow_artifact_root: "${mlflow_artifact_root}"

${sa_annotations}
