odahuFlowVersion: "${odahuflow_version}"
imagesRegistry: "${docker_repo}/"
dockerSecret: "${docker_secret}"
logLevel: debug

ingress:
  enabled: true
  globalDomain: "${cluster_domain}"
  tlsEnabled: ${ingress_tls_enabled}
  tlsSecretName: "${ingress_tls_secret_name}"

security:
  enabled: true
  integration: oauth2_proxy
  mesh_authn: "${oauth_mesh_enabled}"

feedback:
  enabled: true

api:
  replicas: 2
  env:
    VAULT_CACERT: /vault/tls/ca.crt

  volumeMounts:
    - name: vault-tls
      mountPath: /vault/tls

  volumes:
    - name: vault-tls
      secret:
        secretName: vault-tls

metrics:
  enabled: true
  dashboardFolder: /tmp/dashboards/odahu-flow

${connections}

${config}

resource_uploader_sa:
  client_id: ${resource_uploader_sa.client_id}
  client_secret: ${resource_uploader_sa.client_secret}

oauth_oidc_issuer_url: ${oauth_oidc_issuer_url}