odahuFlowVersion: "${odahuflow_version}"
imagesRegistry: "${docker_repo}/"
dockerSecret: "${docker_secret}"
logLevel: debug

edge:
  knative_namespace: "${knative_namespace}"
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "1024m"

ingress:
  enabled: true
  globalDomain: "${cluster_domain}"
  tlsEnabled: ${ingress_tls_enabled}
  tlsSecretName: "${ingress_tls_secret_name}"

security:
  enabled: true
  integration: oauth2_proxy
  mesh_authn: "${oauth_mesh_enabled}"

feedback:
  enabled: true

${api_configuration}

metrics:
  enabled: true
  dashboardFolder: /tmp/dashboards/odahu-flow

${connections}

${config}

${toolsConfig}

resource_uploader_sa:
  client_id: ${resource_uploader_sa.client_id}
  client_secret: ${resource_uploader_sa.client_secret}

oauth_oidc_issuer_url: ${oauth_oidc_issuer_url}
