defaultScopes: "${default_scopes}"
defaultSA: "${default_sa}"
serviceAccountName: "${sa_name}"

image:
  repository: "${image_repo}"
  tag: "${image_tag}"
  pullPolicy: IfNotPresent

fullnameOverride: "${name}"

daemonset:
  hostPort: ${host_port}
  containerPort: ${container_port}

${tolerations}
