fullnameOverride: knative
knative:
  serving:
    create: true
    spec:
      config:
        deployment:
          progressDeadline: "500s"
        features:
          kubernetes.podspec-affinity: "enabled"
          kubernetes.podspec-nodeselector: "enabled"
          kubernetes.podspec-tolerations: "enabled"
    # spec:
    #   config:
    #     defaults:
    #       revision-timeout-seconds: 300
    #     observability:
    #       metrics.backend-destination: prometheus
    #     autoscaler:
    #       stable-window: "60s"
    #       container-concurrency-target-default: 100
  eventing:
    create: false
