sync:
  volume: "airflow-dags"
  subPath: "${subpath}"   
  target: "gcs"
  gcs:
    bucket: "${data_bucket_name}"
    region: "${data_bucket_region}"
    authorization: "gwi"

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "${syncer_sa}"

