{{- if eq .Values.output.target "s3" }}
{{- if eq .Values.output.s3.authorization "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    {{- include "fluentd.helm-labels" (dict "component" "fluentd" "root" .) | nindent 4 }}
type: Opaque
data:
  AWSKeyID: "{{ required "AWS Access Key ID is required for secret-based auth." .Values.output.s3.AWSKeyID | b64enc }}"
  AWSSecretKey: "{{ required "AWS Secret Access Key is required for secret-based auth." .Values.output.s3.AWSSecretKey | b64enc }}"
{{- end }}
{{- end }}
{{- if eq .Values.output.target "gcs" }}
{{- if eq .Values.output.gcs.authorization "keyfile" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-keyfile"
  labels:
    component: "odahu-flow-fluentd"
    {{- include "fluentd.helm-labels" (dict "component" "fluentd" "root" .) | nindent 4 }}
data:
  keyfile.json: |
    {
      "type": "service_account",
      "project_id": "{{ .Values.output.gcs.project }}",
      "private_key_id": "{{ .Values.output.gcs.private_key_id }}",
      "private_key": "{{ .Values.output.gcs.private_key }}",
      "client_email": "{{ .Values.output.gcs.client_email }}",
      "client_id": "{{ .Values.output.gcs.client_id }}",
      "auth_uri": "{{ .Values.output.gcs.auth_uri }}",
      "token_uri": "{{ .Values.output.gcs.token_uri }}",
      "auth_provider_x509_cert_url": "{{ .Values.output.gcs.auth_provider_x509_cert_url }}",
      "client_x509_cert_url": "{{ .Values.output.gcs.client_x509_cert_url }}"
    }

{{- end }}
{{- end }}
{{- if eq .Values.output.target "azureblob" }}
{{- if eq .Values.output.azureblob.authorization "accesskey" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    {{- include "fluentd.helm-labels" (dict "component" "fluentd" "root" .) | nindent 4 }}
type: Opaque
data:
  AzureStorageAccount: "{{ required "Azure Storage Account Name" .Values.output.azureblob.AzureStorageAccount | b64enc }}"
  AzureStorageAccessKey: "{{ required "Azure Storage Access Key (Primary or Secondary)" .Values.output.azureblob.AzureStorageAccessKey | b64enc }}"
{{- end }}
{{- if eq .Values.output.azureblob.authorization "sastoken" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    {{- include "fluentd.helm-labels" (dict "component" "fluentd" "root" .) | nindent 4 }}
type: Opaque
data:
  AzureStorageAccount: "{{ required "Azure Storage Account Name" .Values.output.azureblob.AzureStorageAccount | b64enc }}"
  AzureStorageSasToken: "{{ required "Azure Storage SAS Token" .Values.output.azureblob.AzureStorageSasToken | b64enc }}"
{{- end }}
{{- end }}
