{
 "title": "NVIDIA GPU Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "tags": [
  "GPU",
  "Hardware"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "gpuuuid",
    "label": "GPU",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, UUID)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{UUID=~\"$gpuuuid\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature and power usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}} temperature"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}} power"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum (DCGM_FI_DEV_POWER_USAGE{UUID=~\"$gpuuuid\"})"
    }
   ]
  },
  {
   "title": "GPU Streaming Multiprocessor clocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory clock frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory utilization (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer memory consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}} used"
    },
    {
     "expr": "DCGM_FI_DEV_FB_FREE{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}} free"
    }
   ]
  },
  {
   "title": "Data transmitted through PCIe",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_PCIE_TX_THROUGHPUT{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}} TX"
    },
    {
     "expr": "DCGM_FI_DEV_PCIE_RX_THROUGHPUT{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}} RX"
    }
   ]
  },
  {
   "title": "GPU Encoder/Decoder Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_ENC_UTIL{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}} encoder"
    },
    {
     "expr": "DCGM_FI_DEV_DEC_UTIL{UUID=~\"$gpuuuid\"}",
     "legendFormat": "GPU{{gpu}} decoder"
    }
   ]
  }
 ]
}