apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "knative.labels" (dict "root" . "name" "activator") | nindent 4 }}
  name: config-tracing
  namespace: {{ .Release.Namespace }}
{{- if .Values.config.tracing }}
data:
  {{ toYaml .Values.config.tracing | nindent 2 }}
{{ else }}
data: {}
{{- end }}


