apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "activator") | nindent 4 }}
  name: activator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
        {{- include "knative.labels" (dict "root" . "name" "activator") | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
          {{- include "knative.labels" (dict "root" . "name" "activator") | nindent 8 }}
    spec:
      containers:
        - args:
            - -logtostderr=false
            - -stderrthreshold=FATAL
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
          image: {{ .Values.activator.image }}
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: k-kubelet-probe
                  value: activator
              path: /healthz
              port: 8012
          name: activator
          ports:
            - containerPort: 8012
              name: http1-port
            - containerPort: 8013
              name: h2c-port
            - containerPort: 9090
              name: metrics-port
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: k-kubelet-probe
                  value: activator
              path: /healthz
              port: 8012
          resources:
                {{- toYaml .Values.activator.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/config-logging
              name: config-logging
            - mountPath: /etc/config-observability
              name: config-observability
      serviceAccountName: controller
      volumes:
        - configMap:
            name: config-logging
          name: config-logging
        - configMap:
            name: config-observability
          name: config-observability