apiVersion: v1
kind: Service
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "activator") | nindent 4 }}
  name: activator-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8012
    - name: http2
      port: 81
      protocol: TCP
      targetPort: 8013
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: activator
  type: ClusterIP