---
# https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml

clusterName: "${cluster_name}"
nodeGroup: "${node_group}"
masterService: "${cluster_name}-${node_group}"

roles:
  master: "true"
  ingest: "true"
  data: "true"

resources:
  requests:
    cpu: "1"
    memory: "${es_mem}Gi"
  limits:
    cpu: "1"
    memory: "${es_mem}Gi"

initResources: {}

sidecarResources: {}

esJavaOpts: "-Xmx${es_mem / 2}g -Xms${es_mem / 2}g"

replicas: "${es_replicas}"

# readinessProbe minimal viable healthcheck
clusterHealthCheckParams: "timeout=1s"

esConfig:
 elasticsearch.yml: |
   xpack.monitoring.collection.enabled: true

persistence:
  enabled: true
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: "${storage_size}"

rbac:
  create: true

protocol: http
httpPort: 9200
transportPort: 9300

service:
  type: ClusterIP
  httpPortName: http
  transportPortName: transport

updateStrategy: OnDelete

sysctlVmMaxMapCount: 262144

sysctlInitContainer:
  enabled: true
