---
# https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml

elasticsearchHosts: "${es_service_url}"

fullnameOverride: "kibana"

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

kibanaConfig:
  kibana.yml: |
    server:
      basePath: /kibana
      rewriteBasePath: false
    xpack:
      monitoring.kibana.collection.enabled: true

serverHost: "0.0.0.0"
protocol: "http"
httpPort: 5601
healthCheckPath: "/app/kibana"

updateStrategy:
  type: "Recreate"

service:
  type: "ClusterIP"
  port: 5601

${ingress_config}

image: "${kibana_image}"
imageTag: "${kibana_image_tag}"
