---
# https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml

elasticsearchHosts: "${es_service_url}"

fullnameOverride: "kibana"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Allows you to add any config files in /usr/share/kibana/config/
# such as kibana.yml
kibanaConfig:
  kibana.yml: |
    server.basePath: /kibana
    server.rewriteBasePath: false

serverHost: "0.0.0.0"
protocol: http
httpPort: 5601
healthCheckPath: "/app/kibana"

updateStrategy:
  type: "Recreate"

service:
  type: ClusterIP
  port: 5601

${ingress_config}

image: "${kibana_image}"
imageTag: "${kibana_image_tag}"
