---
# https://github.com/elastic/helm-charts/blob/master/logstash/values.yaml
secretMounts:
  - name: logstash-gke-sa
    secretName: logstash-gke-sa
    path: /credentials

fullnameOverride: "logstash"
image: "gcr.io/or2-msq-epmd-legn-t1iylu/odahu/odahu-flow-logstash-oss"
imageTag: ${version}

imagePullSecrets:
  - name: repo-json-key

replicas: ${logstash_replicas}

# Allows you to add any config files in /usr/share/logstash/config/
# such as logstash.yml and log4j2.properties
logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0

# Allows you to add any pipeline files in /usr/share/logstash/pipeline/
### ***warn*** there is a hardcoded logstash.conf in the image, override it first
logstashPipeline:
  logstash.conf: |
    input {
      google_cloud_storage {
        interval => 60
        bucket_id => "${bucket}"
        file_matches => "logs/.*\.txt"
        codec => "json"
        json_key_file => "/credentials/logstash-gke-sa"
      }
    }
    output {
      elasticsearch {
        hosts => ["${es_service_url}"]
        index => "logstash-%%{+YYYY.MM.dd}"
      }
    }

logstashJavaOpts: "-Xmx1g -Xms1g"

resources:
  requests:
    cpu: "100m"
    memory: "1536Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi

rbac:
  create: true

updateStrategy: OnDelete

httpPort: 9600

service:
  type: ClusterIP
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
