fullnameOverride: oauth2-proxy
 
image:
  repository: ${oauth_image_repository}
  tag: ${oauth_image_tag}
 
config:
  clientID: "${oauth_client_id}"
  clientSecret: "${oauth_client_secret}"
  cookieSecret: "${oauth_cookie_secret}"
  configFile: |
    provider = "iodc"
    redirect_url = "${oauth_redirect_url}"
    oidc_issuer_url = "${oauth_oidc_issuer_url}"
    whitelist_domains = "${domain_name}"
    email_domains = "*"
    skip_provider_button = true
    scope = "${oauth_oidc_scope}"
    http_address = "0.0.0.0:4180"
 
    cookie_domain = "${domain_name}"
    cookie_expire = "${oauth_cookie_expire}"
    cookie_secure = true
 
    set_xauthrequest = true
    set_authorization_header = true
    pass_authorization_header = true
    pass_access_token = true
    pass_user_headers = true
    skip_jwt_bearer_tokens = true
    extra_jwt_issuers = "${oauth_oidc_issuer_url}=${oauth_oidc_audience}"

ingress:
  path: /oauth2
  enabled: true
  hosts:
    - ${domain_name}
  tls:
    - secretName: ${ingress_tls_secret_name}
      hosts:
        - ${domain_name}
 
service:
  port: 4180
 
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

httpScheme: http

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  livenessProbe: 30
  
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 30
