apiVersion: v1
kind: ConfigMap
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "controller") | nindent 4 }}
  name: config-network
  namespace: {{ .Release.Namespace }}
        {{- if .Values.config.network }}
data:
        {{ toYaml .Values.config.network | nindent 2 }}
        {{ else }}
data: {}
        {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "controller") | nindent 4 }}
  name: config-deployment
  namespace: {{ .Release.Namespace }}
        {{- if .Values.config.deployment }}
data:
        {{ toYaml .Values.config.deployment | nindent 2 }}
        {{ else }}
data: {}
        {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "controller") | nindent 4 }}
  name: config-gc
  namespace: {{ .Release.Namespace }}
        {{- if .Values.config.gc }}
data:
        {{ toYaml .Values.config.gc | nindent 2 }}
        {{ else }}
data: {}
        {{- end }}