apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "controller") | nindent 4 }}
  name: controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
        {{- include "knative.labels" (dict "root" . "name" "controller") | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
          {{- include "knative.labels" (dict "root" . "name" "controller") | nindent 8 }}
    spec:
      containers:
        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
          image: {{ .Values.controller.image }}
          name: controller
          ports:
            - containerPort: 9090
              name: metrics
          resources:
                {{ toYaml .Values.controller.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/config-logging
              name: config-logging
      serviceAccountName: controller
      volumes:
        - configMap:
            name: config-logging
          name: config-logging