apiVersion: v1
kind: Service
metadata:
  labels:
        {{- include "knative.labels" (dict "root" . "name" "controller") | nindent 4 }}
  name: controller
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: controller