apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-pipelines-webhook
  name: tekton-pipelines-webhook
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: tekton-pipelines-webhook