---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
    monitoring: prometheus
  name: prometheus-grafana-datasource
  namespace: ${namespace}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://${prometheus_name}-prometheus:9090/
      access: proxy
      isDefault: true

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring: prometheus
  name: grafana
  namespace: ${namespace}
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: service
  namespaceSelector:
    matchNames:
    - ${namespace}
  selector:
    matchLabels:
      app: grafana

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring: prometheus
  name: odahuflow-monitoring-rule
  namespace: ${namespace}
spec:
  groups:
  - name: odahuflow
    rules:
    - alert: HighModelResponseTime
      annotations:
        message: 'Model [name: "{{" $labels.model_name "}}", version: "{{" $labels.model_version "}}"] has response time more than 1 second.'
      expr: histogram_quantile(0.95, sum(rate(odahuflow_model_request_time_bucket[5m])) by (le, pod, model_name, model_version)) > 1
      for: 2m
      labels:
        severity: warning
